title: Mayank Vikash
description: I am passionate to learn about how technologies work, I will post about my learning here.
show_downloads: false
google_analytics: UA-239529646-1
theme: jekyll-theme-cayman
url: https://mayankvikash.ml/
baseurl: ''
---
permalink: /404.html
---

plugins:
  - jekyll-sitemap


